# Generated by Django 5.2.4 on 2025-08-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetApp', '0004_doctor_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la cita'),
        ),
    ]
